name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-readme:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master # do NOT replace with anything else
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }} 
          GH_TOKEN: ${{ secrets.ALLOW_READ_WAKA }}
          SECTION_NAME: "Wakatime"
          SHOW_LINES_OF_CODE: true
          SHOW_TOTAL_CODE_TIME: true
          SHOW_PROFILE_VIEWS: true
          SHOW_LANGUAGE: true
          SHOW_OS: true
          SHOW_SHORT_INFO: true
